### ISSUE TITLE
Gnome-pomodoro freezes on arch (gnome 3.30)

### ISSUE THREAD

**Issue by linusheinz** [codito/gnome-pomodoro#380]
After compiling gnome-pomodoro from the 3.30 branch it freezes every time short after opening it 
![screenshot from 2018-10-13 12-35-23](https://user-images.githubusercontent.com/20044115/46904466-cce19000-cee4-11e8-9fca-234cfe9f35a4.png)

**Comment by linusheinz** [comment]
now it works

**Comment by afromankenobi** [comment]
Hi!

This is because probably the path `gnome-pomodoro` does not exists in the path `/home/linus/.local/share/`

I fixed it temporarily fix this issue by creating the folder with `mkdir ~/.local/share/gnome-pomodoro`

I'm pretty new to Vala but i'm trying to make this automagically on https://github.com/codito/gnome-pomodoro/blob/master/lib/application.vala#L274

@codito are you ok with this? i don't really know if this is the behaviour that you expect.

**Comment by codito** [comment]
@kamilprusko

**Comment by amiklosi** [comment]
@linusheinz how did you make it work?

**Comment by codito** [comment]
Does ff286e47523caa139408b776d5559f1d2f758c67 fix this? It is already part of `0.14.0` release.

**Comment by raxod502** [comment]
I have version 0.14.0 of gnome-pomodoro with version 3.30.2 of gnome-shell on Manjaro and I still see a freeze on launch. If I delete `~/.local/share/gnome-pomodoro` first, then it recreates it with `database.sqlite{,-shm,-wal}`. Upon killing and relaunching I see the same behavior but with this message:

```
** (gnome-pomodoro:27899): CRITICAL **: 11:57:16.556: application.vala:308: Failed to migrate database: Error creating directory /home/raxod502/.local/share/gnome-pomodoro: File exists
```

**Comment by RuubixO** [comment]
I also have issues using on fedora 29. It will lock up if I click more than once or two. It's menu on the gnome bar will not show.

**Comment by raxod502** [comment]
It's not clear to me exactly what I did to make gnome-pomodoro work, but at some point it started working. Some combination of restarting and reinstalling and deleting the database.

**Comment by linusheinz** [comment]
This seems to be an issue on all relatively up to date distros and the same as  #390.
Is this project actively maintained ? Because the issue persisted for the last couple of months.

**Comment by psukys** [comment]
@RuubixO downgrading to `gnome-shell-extension-pomodoro-0.13.4-5.fc29` makes it work (even though, as expected, new features are missing)

**Comment by FelixSchwarz** [comment]
> downgrading to `gnome-shell-extension-pomodoro-0.13.4-5.fc29` makes it work (even though, as expected, new features are missing)

Here is my workaround for Fedora:
- Install an old version of gnome-pomodoro (`sudo dnf downgrade gnome-shell-extension-pomodoro-0.13.4-5.fc29`)
- start the application (`$ gnome-pomodoro`)
- update the application to 0.14.0 (`sudo dnf update`)
- log out from gnome shell
- after the next login gnome-pomodoro should work fine

I'm not sure what is causing this and where the state is stored exactly but somehow the old version initializes something and it continues to work afterwards.

**Comment by kiview** [comment]
I'm seeing a similar problem on Fedora 29.

**Comment by LenzGr** [comment]
FWIW, I installed `gnome-shell-extension-pomodoro-1:0.14.0-3.fc29.x86_64` from the Fedora 29 repository and am unable to use it because it freezes. Restarting gnome-shell didn't help in my case. How can we provide more details to get this resolved?

**Comment by davidCarlos** [comment]
Apparently it's a permition problem. If I run gnome-pomodoro with sudo it works.

**Comment by mcnelson** [comment]
Can't quite get it working for me. Freezing problem too. Tried using sudo but it complains about the display. Tried passing in `--display=:0.0` and `--display=:0` and still doesn't like it. Fedora 30.

**Comment by pabloubal** [comment]
> Apparently it's a permition problem. If I run gnome-pomodoro with sudo it works.

Just made it work with sudo. Thanks @davidCarlos, I didn't event think about sudoing it.
Is there a workaround for avoiding the use of sudo?

**Comment by jwilger** [comment]
"This application seems to have bugs, and I can't launch it. Let me just try running it with sudo..."

Really? Don't ever do this, folks. That's like security 101 level material right there.

**Comment by tuxedotje** [comment]
Works fine on Fedora 32 beta  Freezes on Fedora 31 WHY?

**Comment by iootaa** [comment]
It also freezes with Debian 10 + gnome-shell 3.30.2-11~deb10u1.0tails1

Here is what appears in the terminal when I launch `gnome-pomodoro`

`application.vala:308: Failed to migrate database: Erreur lors de la création du répertoire /home/amnesia/.local/share/gnome-pomodoro : Le fichier existe`

I had to restart gnome-shell with
- Ctrl + Alt + F3
- pkill gnome-shell

Then it works fine (except the stats but that's another problem)

**Comment by harrysolorzano** [comment]
Solution, After installing it, you have to restart the system.

**Comment by iootaa** [comment]
Glad to hear that @harrysolorzano ! But this solution is not possible for Live OS like Tails: https://tails.boum.org

**Comment by iootaa** [comment]
A workaround: start with `gnome-pomodoro --no-default-window` and use it from the top-bar icon (on the top-right corner of the screen)

**Comment by ClaudioCavalcanteVas** [comment]
> Works fine on Fedora 32 beta Freezes on Fedora 31 WHY?
> Solution is simple::
> Restart your computer after install.
> Just restart your computer after install, and do CTRL-ALT-P
> works

it works for me after restart my computer

**Comment by c7hm4r** [comment]
`gnome-pomodoro` freezes still 3s after start.

- Fedora 35; BTRFS; clean user account
- logging out and in again does *not* help
- nothing is shown on STDOUT/-ERR

**Comment by OlgaMaciaszek** [comment]
Same here. Restart worked for me on an earlier version of Fedora, and possibly the Pomodoro app. I'm setting up a new machine and restarting does not help things anymore.

**Comment by rbarte** [comment]
The same here on Fedora 35 and gnome-pomodoro 0.20.0.
